### ISSUE TITLE
I got this error. I followed all the steps

### ISSUE THREAD

**Issue by cloud3799** [Shoot/SpotifyChecker#1]
File "app.py", line 32
    print(f"{username}:{password} | {colorama.Fore.RED} DEAD ACC")
                                                                ^
SyntaxError: invalid syntax

**Comment by Shoot** [comment]
What version of Python are you using? If it is below 3.6 perhaps the issue is that the f-strings are not working.

**Comment by Shoot** [comment]
What version of Python are you using? If it is below 3.6 perhaps the issue is that the f-strings are not working.

**Comment by cloud3799** [comment]
I’m using version 3.7

**Comment by cloud3799** [comment]
Ok I got it working
