### ISSUE TITLE
Possible to change password ?

### ISSUE THREAD

**Issue by GaoangLiu** [Shoot/SpotifyChecker#2]
Hi, Shoot, 

I'm a newcomer to Python and learning web scraping recently. I have tried to login Spotify with Python but constantly failed until I saw your code, it's working like a magic. 

I have this question:  is it possible to change my account password with this `requests.Session().post`  and `https://accounts.spotify.com/api/` thing? If so, what arguments should I pass to the `post` method and which URL link should I use?

Thanks.

**Comment by Shoot** [comment]
I'm not sure if you're able to change your password directly through the Spotify API. However, I'd recommend looking [here](https://www.spotify.com/us/account/change-password/), namely at the form below, as you could probably replicate the request to do so.
![](https://i.imgur.com/tr45mDG.png)

**Comment by GaoangLiu** [comment]
Thank you. I will try it. 👍
